<?php
/**
 * Created by PhpStorm.
 * User: batanov.pavel
 * Date: 12.08.2015
 * Time: 10:48
 */

namespace ScayTrase\SmsDeliveryBundle\Tests\fixtures;

use ScayTrase\SmsDeliveryBundle\SmsDeliveryBundle;
use Symfony\Bundle\FrameworkBundle\FrameworkBundle;
use Symfony\Component\Config\Loader\LoaderInterface;
use Symfony\Component\HttpKernel\Bundle\BundleInterface;
use Symfony\Component\HttpKernel\Kernel;

class KernelForTest extends Kernel
{
    /** @var  string */
    private $config;

    /**
     * Constructor.
     *
     * @param string $environment The environment
     * @param bool $debug Whether to enable debugging or not
     *
     * @api
     */
    public function __construct($environment, $debug, $config = null)
    {
        parent::__construct($environment, $debug); // TODO: Change the autogenerated stub
        $this->config = $config;
    }

    /**
     * Returns an array of bundles to register.
     *
     * @return BundleInterface[] An array of bundle instances.
     *
     * @api
     */
    public function registerBundles()
    {
        return array(
            new FrameworkBundle(),
            new SmsDeliveryBundle(),
        );
    }

    /**
     * Loads the container configuration.
     *
     * @param LoaderInterface $loader A LoaderInterface instance
     *
     * @api
     */
    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        if (null != $this->config) {
            $loader->load($this->config);
        }

        $loader->load(__DIR__ . '/config/default.yml');
    }
}
